CONTACT:
  email: john.doe@john.com
  person: John Doe
LOCAL:
    temp-directory:
    memory: 4g
    raw_data:
    results: results
META:
    species:
        SPECIES_ONE:
            build:
            release:
    ratio: 0.2
    reference-directory:
    gtf_biotypes: gtf_biotypes.yaml

FILTER:
    barcode-whitelist: ''
    5-prime-smart-adapter: ''
    cell-barcode:
        start:
        end:
    UMI-barcode:
        start:
        end:
    cutadapt:
        adapters-file:
        R1:
            quality-filter: 20
            maximum-Ns: 1
            extra-params: ''
        R2:
            quality-filter: 20
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
EXTRACTION:
    LOCUS:
        - CODING
        - UTR
    strand-strategy: SENSE
    UMI-edit-distance: 1
    minimum-counts-per-UMI: 0
DEBUG: False