site_name: dropSeqPipe
theme: readthedocs
repo_name: 'GitHub'
repo_url: https://github.com/Hoohm/dropSeqPipe
nav:
  - 'index.md'
  - 'Setting-up-an-experiment.md'
  - 'Running-dropSeqPipe.md'
  - 'Plots.md'
  - 'Output_misc.md'
  - 'CHANGELOG.md'
  - 'Specific-chemistries.md'
  - 'FAQ.md'

google_analytics:
  - 'UA-128943644-1'
  - 'auto'
